home:
    path: /
    controller: App\Controller\HomeController::home
path_new:
    path: /path/new
    controller: App\Controller\PathController::new
path_index:
    path: /path/index
    controller: App\Controller\PathController::index
register:
    path: /user/new
    controller: App\Controller\UserController::new